AWSTemplateFormatVersion: '2010-09-09'
Resources:
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "arn:aws:s3:::dpk-glue-bucket/*"
  SampleETLJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: s3://dpk-glue-bucket/scripts/sample_etl_job.py
      Role: !GetAtt GlueJobRole.Arn
      DefaultArguments:
        "--TempDir": "s3://dpk-glue-bucket/temp/"
        "--job-language": "python"
      GlueVersion: "4.0"
      WorkerType: G.1X
      NumberOfWorkers: 2
      MaxRetries: 0
      Timeout: 60